import { createContext } from "react";

export const CheatSheet = createContext([
    { title: "ЧИСЛА", text: "", example: "", id: 0.1 },
    { title: "Вызвать 255 шеснацатиричным способом", text: "console.log(0xff);", example: "", id: 1 },
    { title: "Вызвать 255 восмиричным способом", text: "console.log(0o377);", example: "", id: 2 },
    { title: "Вызвать 238 двоичным способом", text: "console.log(0b11101110);", id: 3 },
    { title: "Math -", text: "Округление числа  ", example: "let num = 1.12345;", id: 4 },
    { title: "Math.round-", text: "до ближайшего целого числа ", example: "let numOne = Math.round(num ); = 1", id: 5 },
    { title: "Math.floor", text: " в меньшую сторону", example: "let numOne = Math.floor(num ); = 1", id: 6 },
    { title: "Math.ceil ", text: "в большую сторону", example: "let numOne = Math.ceil(num ); = 2", id: 7 },
    { title: "Math.random()", text: " случайное число включая 0 до 1 не включая", example: "console.log(Math.random());", id: 8 },
    { title: "Math.max()", text: "наибольшее число из перечисленных", example: "console.log(Math.max(1, 2, 4, 5, 67, 66));", id: 9 },
    { title: "Math.min() ", text: " наименьшее число из перечисленных", example: "console.log(Math.min(1, 2, 4, 5, 67, 66));", id: 10 },
    { title: "Math.abs()", text: "Math.abs()", example: "console.log(Math.abs(-58));", id: 11 },
    { title: "Math.pow() ", text: " возведение числа в степень", example: "console.log(Math.pow(n,p)); n - число p - в степени", id: 12 },
    { title: ".trim() ", text: " вырезание пробелов 'лишних' с переди и с зади", example: "", id: 13 },
    { title: ".repeat() ", text: " Повторение", example: "что.repeat(сколько раз)", id: 14 },
    { title: "num.toFixed() ", text: "- количество знаков после запятой надо сократить", example: "let numOne = num.toFixed(2); Но переменная станет strihg, вылечить можно +num.toFixed(2)", id: 15 },
    { title: "Number.EPSILON", text: "бесконечно малое число для исправления проблемы неточных чисел", example: "problem =+ problem.toFixed(1);// лекарство НО строка, которая лечится +", id: 17 },
    { title: "parseInt", text: "покажет число до возникновения ошибки или nan", example: "let str = '0xff'; str = parseInt('0xff', 16); Второй параметр переводящий число в 2ичный , 8ричный, 16ричный вид НЕОБЯЗАТЕЛЕН", id: 18 },
    { title: "parseFloat", text: "покажет число c плавающей запятой до возникновения ошибки или nan", example: "let value = '158.35px';  console.log(parseFloat(value));", id: 19 },
    { title: "toString", text: "вернёт в строковом виде", example: "console.log(num.toString(16));//шеснадцатиричное; console.log(num.toString(2));//двоичное; console.log(num.toString(8));//восьмиричное", id: 20 },
    { title: "isNaN", text: "Проверка на равенство NAN", example: "let vetvl = 58 / 'Aleksei'; if (isNaN(vetvl)) {console.log('Результат выражения NaN'); }", id: 21 },
    { title: "Строка", text: "", example: "", id: 22 },
    { title: "let text = 'Если б мишки были пчёлы';", text: "", example: "", id: 23 },
    { title: ".length", text: "количество символов", example: "console.log(text.length);", id: 24 },
    { title: "вывести нужный по счёту символ", text: "console.log(text[0])", example: "console.log(text[10]);", id: 25 },
    { title: "вывести нужный по счёту символ но с конца", text: "console.log(text[text.length - 1])", example: "", id: 26 },
    { title: ".toUpperCase()", text: "ВЕРХНИЙ РЕГИСТР", example: "console.log(text.toUpperCase());", id: 27 },
    { title: "console.log(text.toUpperCase());", text: "console.log(text.toUpperCase());", example: "console.log(text.toLowerCase());", id: 28 },
    { title: ".indexOf()", text: "поиск покажет где, поиск начиная с № символа", example: "console.log(text.indexOf( 'шки'));  console.log(text.indexOf(' шки',10));", id: 29 },
    { title: ".includes()", text: "поиск булевый ответ; поиск начиная с № символа булевый ответ", example: "console.log(text.includes('шки')); console.log(text.includes('шки', 10)); ", id: 30 },
    { title: ".startsWith()", text: ".startsWith()", example: "console.log(text.startsWith('Есл'));", id: 31 },
    { title: ".endsWith()", text: " поиск с конца, булевый ответ", example: "console.log(text.endsWith('чёлы'));", id: 32 },
    { title: "slice()", text: "покажет часть строки", example: "от 2 до 7;  console.log(text.slice(2, 7));", id: 33 },
])